/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jramirez25
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDenominador1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtNumerador1 = new javax.swing.JTextField();
        cmbOperacion = new javax.swing.JComboBox<String>();
        txtDenominador2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtNumerador2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDenominador3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtNumerador3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        txtDenominador4 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        txtParteEntera = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        txtNumerador4 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        cmdLimpiar = new javax.swing.JButton();
        cmdCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("OPERACIONES CON FRACCIONARIOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 400, 50));

        txtDenominador1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtDenominador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDenominador1ActionPerformed(evt);
            }
        });
        txtDenominador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDenominador1KeyTyped(evt);
            }
        });
        jPanel1.add(txtDenominador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 100, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 100, 10));

        txtNumerador1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtNumerador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumerador1ActionPerformed(evt);
            }
        });
        txtNumerador1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerador1KeyTyped(evt);
            }
        });
        jPanel1.add(txtNumerador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 100, 30));

        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sumar", "Restar", "Multiplicar", "Dividir" }));
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 90, 30));

        txtDenominador2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtDenominador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDenominador2KeyTyped(evt);
            }
        });
        jPanel1.add(txtDenominador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 80, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 80, 10));

        txtNumerador2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtNumerador2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumerador2KeyTyped(evt);
            }
        });
        jPanel1.add(txtNumerador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        txtDenominador3.setEditable(false);
        txtDenominador3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(txtDenominador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 80, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 80, 10));

        txtNumerador3.setEditable(false);
        txtNumerador3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPanel1.add(txtNumerador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 80, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Conversión a mixto", 0, 0, new java.awt.Font("Trebuchet MS", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 80, 10));

        txtDenominador4.setEditable(false);
        txtDenominador4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel2.add(txtDenominador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, 30));

        jTextField11.setEditable(false);
        jPanel2.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, 30));

        txtParteEntera.setEditable(false);
        txtParteEntera.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel2.add(txtParteEntera, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 30, 40));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 80, 10));

        txtNumerador4.setEditable(false);
        txtNumerador4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel2.add(txtNumerador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 80, 30));

        jTextField13.setEditable(false);
        jPanel2.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 80, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 160, 140));

        cmdLimpiar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cmdLimpiar.setText("Borrar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 110, 30));

        cmdCalcular.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(601, 415));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        // TODO add your handling code here:
        txtNumerador1.setText("");
        txtNumerador2.setText("");
        txtNumerador3.setText("");
        txtNumerador4.setText("");
        txtParteEntera.setText("");
        txtDenominador1.setText("");
        txtDenominador2.setText("");
        txtDenominador3.setText("");
        txtDenominador4.setText("");
        txtNumerador1.requestFocusInWindow();
        cmbOperacion.setSelectedIndex(0);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void txtNumerador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerador1KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNumerador1KeyTyped

    private void txtDenominador1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDenominador1KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDenominador1KeyTyped

    private void txtNumerador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumerador2KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNumerador2KeyTyped

    private void txtDenominador2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDenominador2KeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtDenominador2KeyTyped

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        // TODO add your handling code here:
            try {
                int op, n1, d1, n2, d2, n3 ,d3;
                Fraccionario f1, f2, f3 = null;

                op = cmbOperacion.getSelectedIndex();
                n1 = Integer.parseInt(txtNumerador1.getText());
                d1 = Integer.parseInt(txtDenominador1.getText());
                n2 = Integer.parseInt(txtNumerador2.getText());
                d2 = Integer.parseInt(txtDenominador2.getText());
           
                f1 = new Fraccionario(n1, d1);
                f2 = new Fraccionario(n2, d2);
                switch (op) {
                    case 0:
                        f3 = f1.sumar(f2);
                        break;
                    case 1:
                        f3 = f1.restar(f2);
                        break;
                    case 2:
                        f3 = f1.multiplicar(f2);
                        break;
                    case 3:
                        f3 = f1.dividir(f2);
                        break;
                }
                if (f3.getNumerador() < 0 && f3.getDenominador() < 0) {
                    n3 = f3.getNumerador() * -1;
                    d3 = f3.getDenominador() * -1;
                    JOptionPane.showMessageDialog(null, "Los signos se cancelan en el resultado porque - * - es +");
                    
                }
                else {
                    n3 = f3.getNumerador();
                    d3 = f3.getDenominador();
                }
                txtNumerador3.setText(""+ n3);
                txtDenominador3.setText(""+ d3);
                if (n3 < d3) {
                    JOptionPane.showMessageDialog(null, "No se puede obtener la conversión de este resultado a"
                            + " número mixto porque no es una fracción impropia");
                    txtParteEntera.setText("");
                    txtNumerador4.setText("");
                    txtDenominador4.setText("");
                } else {
                    txtParteEntera.setText(""+ n3 / d3);
                    txtNumerador4.setText(""+ n3 % d3);
                    txtDenominador4.setText(""+ d3);
                }
            }
            catch (DenominadorCeroException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Hay campo(s) inválido(s)", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtNumerador1.setText("");
                txtNumerador2.setText("");
                txtNumerador3.setText("");
                txtNumerador4.setText("");
                txtParteEntera.setText("");
                txtDenominador1.setText("");
                txtDenominador2.setText("");
                txtDenominador3.setText("");
                txtDenominador4.setText("");
                txtNumerador1.requestFocusInWindow();
                cmbOperacion.setSelectedIndex(0);
            }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void txtNumerador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumerador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumerador1ActionPerformed

    private void txtDenominador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDenominador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDenominador1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField txtDenominador1;
    private javax.swing.JTextField txtDenominador2;
    private javax.swing.JTextField txtDenominador3;
    private javax.swing.JTextField txtDenominador4;
    private javax.swing.JTextField txtNumerador1;
    private javax.swing.JTextField txtNumerador2;
    private javax.swing.JTextField txtNumerador3;
    private javax.swing.JTextField txtNumerador4;
    private javax.swing.JTextField txtParteEntera;
    // End of variables declaration//GEN-END:variables
}
